apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eidodata
  name: eidodataweb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eidodata
      tier: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eidodata
        tier: web
    spec:
      containers:
        - image: gcr.io/streamlit-292317/github_redcican_pycaret-eidodata
          imagePullPolicy: IfNotPresent
          name: eidodata-app
          ports:
            - containerPort: 80
              protocol: TCP