apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eidodata
  name: eidodata
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eidodata
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eidodata
    spec:
      containers:
        - image: gcr.io/streamlit-292317/github_redcican_pycaret-eidodata
          imagePullPolicy: IfNotPresent
          name: pycaret-eidodata-1