name: publish

on: [push]

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.CLOUD_RUN_SA_EMAIL }}
          service_account_key: ${{ secrets.CLOUD_RUN_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GKE_PROJECT }}/hellorun:latest .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GKE_PROJECT }}/hellorun:latest

      - name: Deploy
        run: |
          gcloud run deploy hellorun \
          --region europe-west1 \
          --image gcr.io/${{ secrets.GKE_PROJECT }}/hellorun \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GKE_PROJECT }}